### ISSUE TITLE
:System.IO.FileNotFoundException:“Could not load file or assembly 'Avalonia.Styling, Version=0.10.17.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. 

### ISSUE THREAD

**Issue by nicewillsuccess** [michael-eddy/Avalonia.Extensions#81]
I had this problem after using the package for this project, here is a screenshot of the package
![image](https://github.com/user-attachments/assets/aef790fa-01a7-411b-9cae-822d3032380d)

**Comment by michael-eddy** [comment]
this package is end of support. plz replace it!
